### ISSUE TITLE
can't instal calligra

### ISSUE THREAD

**Issue by nzimas** [adymo/homebrew-kde#33]
Although Calligra builds as expected, it falls to make install.

Here's the relevant verbose

    ==> make install
    /usr/local/Library/ENV/4.3/clang++   -fno-common -Wnon-virtual-dtor -Wno-long-long -Wundef -Wcast-  align -Wchar-subscripts -Wall -W -Wpointer-arith -Wformat-security -Woverloaded-virtual -fno-common -fvisibility=hidden -Werror=return-type -fvisibility-inlines-hidden -Wno-return-type-c-linkage -dynamiclib -Wl,-headerpad_max_install_names -single_module -multiply_defined suppress   -compatibility_version 14.0.0 -current_version 14.0.0 -o ../../lib/libcalligrastageprivate.14.0.0.dylib -install_name /tmp/calligra-Ua5U/build/lib/libcalligrastageprivate.14.dylib CMakeFiles/calligrastageprivate.dir/calligrastageprivate_automoc.cpp.o CMakeFiles/calligrastageprivate.dir/KPrFactory.cpp.o CMakeFiles/calligrastageprivate.dir/KPrDocument.cpp.o CMakeFiles/calligrastageprivate.dir/KPrDeclarations.cpp.o CMakeFiles/calligrastageprivate.dir/KPrPart.cpp.o CMakeFiles/calligrastageprivate.dir/KPrView.cpp.o CMakeFiles/calligrastageprivate.dir/KPrViewModePresentation.cpp.o CMakeFiles/calligrastageprivate.dir/KPrViewModeNotes.cpp.o CMakeFiles/calligrastageprivate.dir/KPrViewModeSlidesSorter.cpp.o CMakeFiles/calligrastageprivate.dir/KPrViewModePreviewPageEffect.cpp.o CMakeFiles/calligrastageprivate.dir/KPrViewModePreviewShapeAnimations.cpp.o CMakeFiles/calligrastageprivate.dir/KPrPresentationTool.cpp.o CMakeFiles/calligrastageprivate.dir/KPrAnimationDirector.cpp.o CMakeFiles/calligrastageprivate.dir/KPrShapeAnimations.cpp.o CMakeFiles/calligrastageprivate.dir/KPrShapeManagerAnimationStrategy.cpp.o CMakeFiles/calligrastageprivate.dir/KPrShapeManagerDisplayMasterStrategy.cpp.o CMakeFiles/calligrastageprivate.dir/KPrPageData.cpp.o CMakeFiles/calligrastageprivate.dir/KPrPage.cpp.o CMakeFiles/calligrastageprivate.dir/KPrMasterPage.cpp.o CMakeFiles/calligrastageprivate.dir/KPrNotes.cpp.o CMakeFiles/calligrastageprivate.dir/KPrSoundData.cpp.o CMakeFiles/calligrastageprivate.dir/KPrSoundCollection.cpp.o CMakeFiles/calligrastageprivate.dir/KPrEventActionData.cpp.o CMakeFiles/calligrastageprivate.dir/KPrEventActionWidget.cpp.o CMakeFiles/calligrastageprivate.dir/KPrPageApplicationData.cpp.o CMakeFiles/calligrastageprivate.dir/KPrShapeApplicationData.cpp.o CMakeFiles/calligrastageprivate.dir/KPrCustomSlideShows.cpp.o CMakeFiles/calligrastageprivate.dir/KPrPresenterViewBaseInterface.cpp.o CMakeFiles/calligrastageprivate.dir/KPrPresenterViewInterface.cpp.o CMakeFiles/calligrastageprivate.dir/KPrPresenterViewSlidesInterface.cpp.o CMakeFiles/calligrastageprivate.dir/KPrPresenterViewToolWidget.cpp.o CMakeFiles/calligrastageprivate.dir/KPrPresenterViewWidget.cpp.o CMakeFiles/calligrastageprivate.dir/KPrEndOfSlideShowPage.cpp.o CMakeFiles/calligrastageprivate.dir/KPrPlaceholderShape.cpp.o CMakeFiles/calligrastageprivate.dir/KPrPlaceholderShapeFactory.cpp.o CMakeFiles/calligrastageprivate.dir/KPrPlaceholderStrategy.cpp.o CMakeFiles/calligrastageprivate.dir/KPrPlaceholderPictureStrategy.cpp.o CMakeFiles/calligrastageprivate.dir/KPrPlaceholderTextStrategy.cpp.o CMakeFiles/calligrastageprivate.dir/KPrPresentationHighlightWidget.cpp.o CMakeFiles/calligrastageprivate.dir/KPrPresentationDrawWidget.cpp.o CMakeFiles/calligrastageprivate.dir/KPrPresentationBlackWidget.cpp.o CMakeFiles/calligrastageprivate.dir/KPrPresentationStrategy.cpp.o CMakeFiles/calligrastageprivate.dir/KPrPresentationHighlightStrategy.cpp.o CMakeFiles/calligrastageprivate.dir/KPrPresentationBlackStrategy.cpp.o CMakeFiles/calligrastageprivate.dir/KPrPresentationStrategyBase.cpp.o CMakeFiles/calligrastageprivate.dir/KPrPresentationToolEventForwarder.cpp.o CMakeFiles/calligrastageprivate.dir/KPrPresentationDrawStrategy.cpp.o CMakeFiles/calligrastageprivate.dir/KPrPageSelectStrategyBase.cpp.o CMakeFiles/calligrastageprivate.dir/KPrPageSelectStrategyFixed.cpp.o CMakeFiles/calligrastageprivate.dir/KPrPageSelectStrategyActive.cpp.o CMakeFiles/calligrastageprivate.dir/KPrDurationParser.cpp.o CMakeFiles/calligrastageprivate.dir/KPrHtmlExport.cpp.o CMakeFiles/calligrastageprivate.dir/KPrHtmlExportUiDelegate.cpp.o CMakeFiles/calligrastageprivate.dir/KPrPicturesImport.cpp.o CMakeFiles/calligrastageprivate.dir/KPrPdfPrintJob.cpp.o CMakeFiles/calligrastageprivate.dir/KPrSlidesSorterDocumentModel.cpp.o CMakeFiles/calligrastageprivate.dir/KPrSlidesManagerView.cpp.o CMakeFiles/calligrastageprivate.dir/KPrCustomSlideShowsModel.cpp.o CMakeFiles/calligrastageprivate.dir/KPrSlidesSorterItemDelegate.cpp.o CMakeFiles/calligrastageprivate.dir/KPrPageLayoutWidget.cpp.o CMakeFiles/calligrastageprivate.dir/commands/KPrAnimationCreateCommand.cpp.o CMakeFiles/calligrastageprivate.dir/commands/KPrAnimationRemoveCommand.cpp.o CMakeFiles/calligrastageprivate.dir/commands/KPrPageEffectSetCommand.cpp.o CMakeFiles/calligrastageprivate.dir/commands/KPrPageLayoutCommand.cpp.o CMakeFiles/calligrastageprivate.dir/commands/KPrEditCustomSlideShowsCommand.cpp.o CMakeFiles/calligrastageprivate.dir/commands/KPrAddCustomSlideShowCommand.cpp.o CMakeFiles/calligrastageprivate.dir/commands/KPrDelCustomSlideShowCommand.cpp.o CMakeFiles/calligrastageprivate.dir/commands/KPrRenameCustomSlideShowCommand.cpp.o CMakeFiles/calligrastageprivate.dir/commands/KPrDeleteSlidesCommand.cpp.o CMakeFiles/calligrastageprivate.dir/commands/KPrEditAnimationTimeLineCommand.cpp.o CMakeFiles/calligrastageprivate.dir/commands/KPrAnimationEditNodeTypeCommand.cpp.o CMakeFiles/calligrastageprivate.dir/commands/KPrReorderAnimationCommand.cpp.o CMakeFiles/calligrastageprivate.dir/commands/KPrReplaceAnimationCommand.cpp.o CMakeFiles/calligrastageprivate.dir/dockers/KPrPreviewWidget.cpp.o CMakeFiles/calligrastageprivate.dir/pageeffects/KPrPageEffectRunner.cpp.o CMakeFiles/calligrastageprivate.dir/pageeffects/KPrPageEffect.cpp.o CMakeFiles/calligrastageprivate.dir/pageeffects/KPrPageEffectStrategy.cpp.o CMakeFiles/calligrastageprivate.dir/pageeffects/KPrPageEffectFactory.cpp.o CMakeFiles/calligrastageprivate.dir/pageeffects/KPrPageEffectRegistry.cpp.o CMakeFiles/calligrastageprivate.dir/animations/KPrAnimationBase.cpp.o CMakeFiles/calligrastageprivate.dir/animations/KPrAnimSet.cpp.o CMakeFiles/calligrastageprivate.dir/animations/KPrAnimate.cpp.o CMakeFiles/calligrastageprivate.dir/animations/KPrAnimateColor.cpp.o CMakeFiles/calligrastageprivate.dir/animations/KPrAnimateMotion.cpp.o CMakeFiles/calligrastageprivate.dir/animations/KPrAnimateTransform.cpp.o CMakeFiles/calligrastageprivate.dir/animations/KPrAnimTransitionFilter.cpp.o CMakeFiles/calligrastageprivate.dir/animations/KPrAnimationFactory.cpp.o CMakeFiles/calligrastageprivate.dir/animations/KPrAnimationCache.cpp.o CMakeFiles/calligrastageprivate.dir/animations/KPrTextBlockPaintStrategy.cpp.o CMakeFiles/calligrastageprivate.dir/animations/KPrShapeAnimation.cpp.o CMakeFiles/calligrastageprivate.dir/animations/KPrAnimationStep.cpp.o CMakeFiles/calligrastageprivate.dir/animations/KPrAnimationSubStep.cpp.o CMakeFiles/calligrastageprivate.dir/animations/KPrAnimationLoader.cpp.o CMakeFiles/calligrastageprivate.dir/animations/KPrAnimationData.cpp.o CMakeFiles/calligrastageprivate.dir/animations/strategy/KPrAnimationValue.cpp.o CMakeFiles/calligrastageprivate.dir/animations/strategy/KPrFormulaParser.cpp.o CMakeFiles/calligrastageprivate.dir/animations/strategy/KPrAnimationAttribute.cpp.o CMakeFiles/calligrastageprivate.dir/animations/strategy/KPrSmilValues.cpp.o CMakeFiles/calligrastageprivate.dir/animations/strategy/KPrAttributeX.cpp.o CMakeFiles/calligrastageprivate.dir/animations/strategy/KPrAttributeY.cpp.o CMakeFiles/calligrastageprivate.dir/animations/strategy/KPrAttributeWidth.cpp.o CMakeFiles/calligrastageprivate.dir/animations/strategy/KPrAttributeHeight.cpp.o CMakeFiles/calligrastageprivate.dir/animations/strategy/KPrAttributeRotate.cpp.o CMakeFiles/calligrastageprivate.dir/pagelayout/KPrPlaceholder.cpp.o CMakeFiles/calligrastageprivate.dir/pagelayout/KPrPageLayout.cpp.o CMakeFiles/calligrastageprivate.dir/pagelayout/KPrPageLayouts.cpp.o CMakeFiles/calligrastageprivate.dir/pagelayout/KPrPageLayoutSharedSavingData.cpp.o CMakeFiles/calligrastageprivate.dir/pagelayout/KPrPlaceholders.cpp.o CMakeFiles/calligrastageprivate.dir/ui/KPrConfigureSlideShowDialog.cpp.o CMakeFiles/calligrastageprivate.dir/ui/KPrConfigurePresenterViewDialog.cpp.o CMakeFiles/calligrastageprivate.dir/ui/KPrPresentationToolWidget.cpp.o CMakeFiles/calligrastageprivate.dir/ui/KPrHtmlExportDialog.cpp.o CMakeFiles/calligrastageprivate.dir/tools/KPrPlaceholderTool.cpp.o CMakeFiles/calligrastageprivate.dir/tools/KPrPlaceholderToolFactory.cpp.o CMakeFiles/calligrastageprivate.dir/KPrViewAdaptor.cpp.o CMakeFiles/calligrastageprivate.dir/KPrPresentationToolAdaptor.cpp.o -F/usr/local/lib -F/usr/local/Cellar/qt/4.8.6/lib ../../lib/libkopageapp.14.0.0.dylib ../../lib/libkowidgets.14.0.0.dylib ../../lib/libkotextlayout.14.0.0.dylib -framework phonon -framework QtOpenGL -framework QtWebKit ../../lib/libkomain.14.0.0.dylib ../../lib/libkowidgets.14.0.0.dylib ../../lib/libkotextlayout.14.0.0.dylib ../../lib/libkotext.14.0.0.dylib ../../lib/libflake.14.0.0.dylib ../../lib/libpigmentcms.14.0.0.dylib ../../lib/libkoplugin.14.0.0.dylib ../../lib/libkowidgetutils.14.0.0.dylib ../../lib/libkoodf.14.0.0.dylib ../../lib/libkundo2.14.0.0.dylib /usr/local/kde4/lib/libkio.5.13.0.dylib -framework QtNetwork -framework QtXml /usr/local/kde4/lib/libkdeui.5.13.0.dylib -framework QtGui -framework QtSvg /usr/local/kde4/lib/libkdecore.5.13.0.dylib -framework QtDBus -framework QtCore -framework Carbon 
cd /tmp/calligra-Ua5U/build/stage/part && /usr/local/Cellar/cmake/3.0.0/bin/cmake -E cmake_symlink_library ../../lib/libcalligrastageprivate.14.0.0.dylib ../../lib/libcalligrastageprivate.14.dylib ../../lib/libcalligrastageprivate.dylib
/usr/local/Cellar/cmake/3.0.0/bin/cmake -E cmake_progress_report /tmp/calligra-Ua5U/build/CMakeFiles  37 38 39 40 41
[ 93%] Built target calligrastageprivate
make: *** [all] Error 2

READ THIS: https://github.com/Homebrew/homebrew/wiki/troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/hapasa/homebrew-kde/issues

**Comment by backvan** [comment]
I'm having almost the identical problem trying to build Calligra.  This shouldn't be this hard.

/usr/local/Cellar/cmake/3.2.3/bin/cmake -E cmake_progress_report /tmp/calligra20150625-701-1i0m8pc/build/CMakeFiles 
[  0%] Built target calligrastageprivate_automoc
make: *** [all] Error 2

I on a MacBoolPro with Yosemite 10.10.3 and Xcode 6.3.2.  "brew doctor" says all is well.  I'm stuck

**Comment by adymo** [comment]
Calligra is no longer part of this repo
