### ISSUE TITLE
Gantlee : SHA1 key

### ISSUE THREAD

**Issue by stephane-lb** [adymo/homebrew-kde#40]
Hi adymo,

I am trying to install kdevelop on my Mac, and I just had this issue : 

``` bash
==> Installing dependencies for kdevelop: grantlee, kdevplatform
==> Installing kdevelop dependency: grantlee
==> Downloading http://gitorious.org/grantlee/grantlee/archive-tarball/master
######################################################################## 100.0%
Error: SHA1 mismatch
Expected: 19763bc1dafb8aa6843660b1dd75fcc7fa67c0f4
Actual: 9f64b3d5579ae32085fa459e44581f21b08469d6
Archive: /Library/Caches/Homebrew/grantlee-0.3.0
To retry an incomplete download, remove the file above.
```

I think you should update gantlee.rb  with the actual key.

Have a good day,

-S-

**Comment by ShinDarth** [comment]
Same problem here, and ```brew install --HEAD grantlee``` didn't solve the issue

**Comment by unix1** [comment]
@ShinDarth have you tried my fix in #48?

**Comment by ShinDarth** [comment]
@unix1 how can I try it? where is located the file grantlee.rb I should edit?

**Comment by unix1** [comment]
@ShinDarth I'm relatively new to this stuff too, I believe they are in `/usr/local/Library/Formula`.

**Comment by ShinDarth** [comment]
which file?

**Comment by ShinDarth** [comment]
it isn't there
