### ISSUE TITLE
SHA1 Mismatch for grantlee dependency

### ISSUE THREAD

**Issue by Tetarchus** [adymo/homebrew-kde#51]
Hi adymo, I've encountered an issue when trying to `brew install kdevelop`:

````
==> Installing grantlee from adymo/homebrew-kde
==> Downloading https://gitorious.org/grantlee/grantlee/archive/v0.5.1.tar.gz
######################################################################## 100.0%
Error: SHA1 mismatch
Expected: 0c89a65397e1e8402e12f586ca5f63309b5e041c
Actual: eea5ef705f6dc04c658e0cd73d30a9c3caf6f070
Archive: /Library/Caches/Homebrew/grantlee-0.5.1.tar.gz
To retry an incomplete download, remove the file above.
````

It seems like this error is occuring again. Would you be able to update the SHA1 for this dependency? Thanks

**Comment by cipriangal** [comment]
You can work around this by modifying your local copy of the grantlee.rb (most likely found under /usr/local/Library/Taps/adymo/homebrew-kde/grantlee.rb ) with the actual SHA1 value.

**Comment by Tetarchus** [comment]
Thanks for that, did not even cross my mind! Solved

**Comment by paytonrules** [comment]
That's great that there's a workaround but shouldn't this get fixed? Not every user is gonna head to github and see this.

**Comment by zfogg** [comment]
+1 https://github.com/adymo/homebrew-kde/pull/52
