### ISSUE TITLE
grantlee fails

### ISSUE THREAD

**Issue by inyun2u** [adymo/homebrew-kde#54]
hi,

"brew install grantlee" failed because of SHA
so tried --HEAD option

https://gist.github.com/anonymous/bd6fda2f5fd2130bb3c1

but line 7
-DKDE_DEFAULT_HOME=Library/Preferences/KDE
looks suspicious

**Comment by bijeebuss** [comment]
Im having the same issue

After using "brew install --HEAD grantlee" I get 

-- Configuring incomplete, errors occurred!
See also "/tmp/grantlee20150404-96947-1wv1efi/build/CMakeFiles/CMakeOutput.log".

But that log file doesn't exist

**Comment by adymo** [comment]
Fixed now. There's a good source of tarballs now.
