### ISSUE TITLE
Cannot install kate

### ISSUE THREAD

**Issue by jordwalke** [adymo/homebrew-kde#55]
Following the instructions do not seem to work. Here's the error. The ftp site is down?

brew install kate
==> Installing kate from adymo/homebrew-kde
==> Installing dependencies for kate: automoc4, giflib, clucene, raptor, rasqal, unixodbc, redland, soprano, shared-desktop-ontologies, intltool, shared-mime-info, attica, strigi, docbook, docbook-xsl, doxygen, qjson, libdbusmenu-q
==> Installing kate dependency: automoc4
==> Downloading ftp://ftp.kde.org/pub/kde/stable/automoc4/0.9.88/automoc4-0.9.88.tar.bz2

curl: (6) Could not resolve host: ftp.kde.org
Error: Failed to download resource "automoc4"
Download failed: ftp://ftp.kde.org/pub/kde/stable/automoc4/0.9.88/automoc4-0.9.88.tar.bz2

**Comment by emisca** [comment]
you need to edit it, and change url to an ftp.kde.org mirror:
brew edit automoc4

find the line with ftp.kde.org and change it to a mirror like ftp://ftp.heanet.ie/mirrors/ftp.kde.org/
I did that with attica, and it worked.

**Comment by jordwalke** [comment]
What's the reason for the ftp being down? Isn't kde pretty well supported?

**Comment by emisca** [comment]
I wasn't able to find a reason, maybe it's superseded by download.kde.org ?

**Comment by tingyu66** [comment]
@emisa +1

Thanks

**Comment by adymo** [comment]
This is fixed in homebrew itself
