### ISSUE TITLE
Make all of this easier.

### ISSUE THREAD

**Issue by jordwalke** [adymo/homebrew-kde#56]
Hi, thanks for getting all of this working, but the setup is currently incredibly complex.

One piece of feedback, it's not clear if the `d-bus` launch is something you need to do once, or be put in your `bashrc`. Also, it's not clear which of the setup instructions have system side effects that need to be undone when removing/uninstalling.

**Comment by adymo** [comment]
Unfortunately, it's going to be easier to setup only with KDE Frameworks 5. For example, Kate devs are now able to provide dmg: http://kate-editor.org/2015/10/21/alpha-kate-kwrite-application-bundles/
