### ISSUE TITLE
Error installing kate

### ISSUE THREAD

**Issue by wxjay** [adymo/homebrew-kde#61]
I get the following error when installing kate using home-brew:

% brew install kate
==> Installing kate from adymo/homebrew-kde
==> Installing dependencies for adymo/kde/kate: akonadi, libical, kdepimlibs, kactivities, kde-runtime
==> Installing adymo/kde/kate dependency: akonadi
==> Downloading http://download.kde.org/stable/akonadi/src/akonadi-1.13.0.tar.bz2
Already downloaded: /Library/Caches/Homebrew/akonadi-1.13.0.tar.bz2
==> cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local/kde4 -Wdev --trace --debug-output -DKDE_DEFAULT_HOME=Library/Preferences/KDE -DCMAKE_PREFIX_PATH=/usr/local/C
==> make
[ 78%] Built target clientcapabilityaggregatortest
Linking CXX executable akdbustest
[ 78%] Built target akstandarddirstest
[ 78%] Built target akdbustest
make: *** [all] Error 2

When running brew doctor, I get the following:
Error: Failed to import: adymo/kde/base_kde_formula
formulae require at least a URL
Error: compile error
/usr/local/Library/Taps/adymo/homebrew-kde/calligra.rb:64: syntax error, unexpected tSTRING_BEG, expecting tAMPER
        system "cmake", *cmake_args, "-DBUNDLE_INSTALL_DIR=."
                                      ^
/usr/local/Library/Taps/adymo/homebrew-kde/calligra.rb:72: syntax error, unexpected tSTRING_BEG, expecting tAMPER
                      "-DBUNDLE_INSTALL_DIR=#{bin}",
                       ^
/usr/local/Library/Taps/adymo/homebrew-kde/calligra.rb:72: syntax error, unexpected ',', expecting kEND

Any help would be appreciated. Thank you.

**Comment by adymo** [comment]
Calligra is no longer part of this repo
