### ISSUE TITLE
Grantlee will not download from its gitorious link.

### ISSUE THREAD

**Issue by Benevolent** [adymo/homebrew-kde#64]
Gitorious is moving to archive.org as it was bought out by Gitlab. surely there is another link we could use? I have seen Grantlee tarballs available from http://downloads.grantlee.org/

**Comment by lylemoffitt** [comment]
For clarity, the solution (until the move is complete) is to perform the following:
```
$ brew edit grantlee
```
Then make the following changes to the `url` and `sha1` lines (comments left for reference):
```
  # url 'https://gitorious.org/grantlee/grantlee/archive/v0.5.1.tar.gz'
  url 'http://downloads.grantlee.org/grantlee-0.5.1.tar.gz'
  # sha1 '0c89a65397e1e8402e12f586ca5f63309b5e041c'
  sha1 'fe7111bcf25d1e3ead8e48f0f1aea91df944e58d'
```

**Comment by adymo** [comment]
This is in master now
